server:
  # port: 0
  port: 9093

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://userdb.cdmg6w0804tc.us-east-2.rds.amazonaws.com/userdb?useSSL=false&serverTimezone=UTC
    username: admin
    password: eusou100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000  # 180000 3 minutos
      refresh-token:
        expiration: 604800000 # 360000 6 min ---604800000 7 days
